#!/bin/sh

TOUCHPAD_ICON="/usr/share/icons/Adwaita/scalable/devices/input-touchpad-symbolic.svg"

state=$(synclient | awk '/TouchpadOff/ {print $3}')

notify_send() {
    notify-send -u low -t 3000 -i $TOUCHPAD_ICON "$1"
}

if [ $state = 0 ]; then
    synclient TouchpadOff=1
    notify_send "Touchpad off"
else
    synclient TouchpadOff=0
    notify_send "Touchpad on"
fi
