#!/bin/bash

set -e

SLEEP_TIME=20
WARN_CAP=40
# CRIT_CAP=15

NOTIFY_ICON_WARN="/usr/share/icons/Adwaita/scalable/status/battery-level-30-symbolic.svg"
NOTIFY_ICON_CRIT="/usr/share/icons/Adwaita/scalable/status/battery-level-10-symbolic.svg"
WAV_LOC=$HOME"/.config/i3/battery_ctl/notif_sound.wav"

get_battery_stats() {
    battery_info="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)"
    percentage="$(sed -n '/percentage:/s/.*:\ *//p' <<< "$battery_info")"
    echo "${percentage:0:-1}"
}

play_sound() {
    paplay "$WAV_LOC" --volume 32768
}

notify_warn() {
    notify-send -u critical -t 5000 -i $NOTIFY_ICON_WARN "Warning! Low battery."
    play_sound
}

notify_crit() {
    notify-send -u critical -t 5000 -i $NOTIFY_ICON_CRIT \
        "Reached critical battery threshold. Hibernating in 3 seconds..."
    play_sound
}

while true; do
    sleep $SLEEP_TIME
    get_battery_stats | {
        read -r status capacity

        if [ "$status" = Discharging ]; then
            # if [ "$capacity" -le $CRIT_CAP ]; then
            #     notify_crit
            #     sleep 3
            #     systemctl hibernate
            #     exit 1
            if [ "$capacity" -le $WARN_CAP ]; then
                notify_warn
            fi
        fi
    }
done
