#!/bin/bash

declare _OPTION_PLAYER="mpv"
declare _OPTION_QUALITY="best"
declare _OPTION_CHAT=false

usage() {
  echo "Usage:" >&2
  echo "  sl [flags] CHANNEL" >&2
}

while getopts "chq::p::" o; do
  case "${o}" in
    c)
      _OPTION_CHAT=true
      ;;
    q)
      _OPTION_QUALITY="${OPTARG}"
      ;;
    p)
      _OPTION_PLAYER="${OPTARG}"
      ;;
    h)
      usage && exit
      ;;
    *)
      usage && exit 1
      ;;
  esac
done

shift $((OPTIND - 1))
declare channel="$1"

if [[ -z "$channel" ]]; then
   echo "Missing an argument: channel" >&2
   exit 1
fi

if [[ "$_OPTION_CHAT" == true ]]; then
  chatterino_7tv -c "$channel" & disown
  # shellcheck disable=SC2064
  trap "kill $!" EXIT
fi

devour streamlink --twitch-low-latency --player="$_OPTION_PLAYER" \
  --hls-live-edge=1 "twitch.tv/$channel" "$_OPTION_QUALITY"
