#!/bin/bash

declare PLAYER="mpv" channel_name="$1"

[[ -z "$channel_name" ]] && \
    echo "Missing an argument: channel name" >&2 && exit 1

[[ "$2" == "-c" ]] && chatterino_7tv -c "$channel_name" & disown

devour streamlink --twitch-low-latency --player="$PLAYER" \
    --hls-live-edge=1 "twitch.tv/$channel_name" best
